-- Network Service Ticketing - initial schema
-- Uses gen_random_uuid() from pgcrypto for UUID primary keys.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username      VARCHAR(64) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    role          VARCHAR(16) NOT NULL CHECK (role IN ('ADMIN', 'TEKNISI')),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- locations (Master Lokasi)
-- ============================================================
CREATE TABLE IF NOT EXISTS locations (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(150) NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- priorities (Master Priority)
-- level: lower number = higher priority (1=Critical .. 4=Low)
-- ============================================================
CREATE TABLE IF NOT EXISTS priorities (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(50) NOT NULL UNIQUE,
    color       VARCHAR(20) NOT NULL DEFAULT 'gray',
    level       INT NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (level)
);

-- ============================================================
-- update_types (Master Update Type)
-- ============================================================
CREATE TABLE IF NOT EXISTS update_types (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(150) NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- ticket_sequences: atomic daily counter used to build ticket IDs
-- date_key format DDMMYY
-- ============================================================
CREATE TABLE IF NOT EXISTS ticket_sequences (
    date_key  CHAR(6) PRIMARY KEY,
    last_seq  INT NOT NULL DEFAULT 0
);

-- ============================================================
-- tickets
-- id format: DDMMYYNNNN (text, generated by application in a
-- single atomic UPSERT against ticket_sequences)
-- ============================================================
CREATE TABLE IF NOT EXISTS tickets (
    id            CHAR(10) PRIMARY KEY,
    location_id   UUID NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    issue_type    VARCHAR(200) NOT NULL,
    priority_id   UUID NOT NULL REFERENCES priorities(id) ON DELETE RESTRICT,
    detail        TEXT,
    status        VARCHAR(16) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN', 'IN_PROGRESS', 'CLOSED')),
    created_by    UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    assigned_to   UUID REFERENCES users(id) ON DELETE RESTRICT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON tickets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON tickets(created_at);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON tickets(priority_id);
CREATE INDEX IF NOT EXISTS idx_tickets_location ON tickets(location_id);

-- ============================================================
-- ticket_updates: progress log / timeline entries
-- ============================================================
CREATE TABLE IF NOT EXISTS ticket_updates (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id       CHAR(10) NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    update_type_id  UUID REFERENCES update_types(id) ON DELETE SET NULL,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ticket_updates_ticket_id ON ticket_updates(ticket_id);

-- ============================================================
-- ticket_attachments: photos, either attached at creation time
-- (ticket_update_id NULL) or attached to a specific progress update
-- ============================================================
CREATE TABLE IF NOT EXISTS ticket_attachments (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id         CHAR(10) NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    ticket_update_id  UUID REFERENCES ticket_updates(id) ON DELETE CASCADE,
    file_path         TEXT NOT NULL,
    original_name     VARCHAR(255) NOT NULL,
    mime_type         VARCHAR(100) NOT NULL,
    size_bytes        INT NOT NULL,
    uploaded_by       UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ticket_attachments_ticket_id ON ticket_attachments(ticket_id);

-- ============================================================
-- ticket_status_history: audit trail of every status transition
-- ============================================================
CREATE TABLE IF NOT EXISTS ticket_status_history (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id     CHAR(10) NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    from_status   VARCHAR(16),
    to_status     VARCHAR(16) NOT NULL,
    changed_by    UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    changed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ticket_status_history_ticket_id ON ticket_status_history(ticket_id);

-- ============================================================
-- updated_at auto-touch trigger (generic)
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_locations_updated_at ON locations;
CREATE TRIGGER trg_locations_updated_at BEFORE UPDATE ON locations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_priorities_updated_at ON priorities;
CREATE TRIGGER trg_priorities_updated_at BEFORE UPDATE ON priorities
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_update_types_updated_at ON update_types;
CREATE TRIGGER trg_update_types_updated_at BEFORE UPDATE ON update_types
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_tickets_updated_at ON tickets;
CREATE TRIGGER trg_tickets_updated_at BEFORE UPDATE ON tickets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
